name: SimplyUHC
main: al.rosenth.SimplyUHC.SimplyUHC
version: 0.0.1
commands:
  uhc:
      description: Basic commands for uhc
      usage: /uhc [start,stop]
  setborder:
      description: Sets the World border
      usage: /setborder maxX,maxY
  scenarios:
      description: Lists the scenarios loaded
      usage: /scenarios